# Data Wrangling for Tableau

## Data Wrangling Objective

The objective of the data wrangling process is to clean, transform, and consolidate the datasets into a structured format suitable for analysis and visualisation. This includes handling unnecessary columns, merging related datasets, creating new calculated features, and ensuring data consistency across all tables.

The processed dataset will then be used to support meaningful exploratory analysis and the development of interactive Tableau dashboards that provide insights into Singapore’s residential property market.

## 1. Dataset Analysis
This Analysis is to get a brief overview on the datasets provided. This can support decision making steps later on when deciding what to do with the datasets to create useful visual insights on Tableau.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Dataset Infomation

In [2]:
POI.info()
Amenities.info()
SM_assets.info()
Sales.info()
Subzones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7795 entries, 0 to 7794
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             7795 non-null   int64
 1   POI_Type       7795 non-null   object
 2   POI_Name       7795 non-null   object
 3   POI_InSubzone  7795 non-null   int64
 4   POI_Latitude   7794 non-null   float64
 5   POI_Longitude  7794 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 365.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PropertyID  2400 non-null   int64
 1   Gym         2395 non-null   float64
 2   Pool        2398 non-null   float64
 3   Playground  2393 non-null   float64
 4   Tennis      2391 non-null   float64
 5   Golf        2245 non-null   object
 6   Cafe        1687 non-null   object
 7   LapPool     2386 non-null   float64
 8   KidsPool    2386 non-null   float64
 9   Squash      2383 non-null   float64
 10  Badminton   2383 non-null   float64
 11  Basketball  2383 non-null   float64
 12  BBQ         2394 non-null   float64
 13  Jacuzzi     2387 non-null   float64
 14  Security    2371 non-null   float64
 15  Salon       1578 non-null   object
 16  Sauna       2289 non-null   object
 17  Shop        2291 non-null   object
dtypes: float64(12), int64(1), object(5)
memory usage: 337.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19095 entries, 0 to 19094
Data columns (total 8 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   PropertyID                               19095 non-null  int64
 1   NumberofSchoolsWithin500Mts              19095 non-null  int64
 2   NumberOfMRTsWithin500Mts                 19095 non-null  int64
 3   NumberOfBusStopsWithin500Mts             19095 non-null  int64
 4   TimeToRafflesByCarInSeconds              19095 non-null  int64
 5   TimeToRafflesByPublicTransportInSeconds  19095 non-null  int64
 6   TimeToAirportByCarInSeconds              19095 non-null  int64
 7   TimeToAirportByPublicTransportInSeconds  19095 non-null  int64
dtypes: int64(8)
memory usage: 1.2 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517591 entries, 0 to 517590
Data columns (total 15 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Id                                517591 non-null  int64
 1   PropertyID                        517591 non-null  int64
 2   PropertyType                      517591 non-null  int64
 3   PropertyTenureType                517591 non-null  int64
 4   PropertyNumberOfFloors            152153 non-null  float64
 5   PropertynumberOfUnits             451278 non-null  float64
 6   PropertyYearOfCompletion          462689 non-null  float64
 7   PropertyInSubzone                 517591 non-null  int64
 8   PropertyLatitude                  517591 non-null  float64
 9   PropertyLongitude                 517591 non-null  float64
 10  FloorNoOfTransactedUnit           517591 non-null  int64
 11  NumberOfBedroomsInTransactedUnit  241531 non-null  float64
 12  TransactedPricePerSqFt            517591 non-null  float64
 13  TransactionType                   517591 non-null  int64
 14  TransactionDate                   517591 non-null  object
dtypes: float64(7), int64(7), object(1)
memory usage: 59.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 323 entries, 0 to 322
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SubzoneId         323 non-null    int64
 1   SubzoneCode       323 non-null    object
 2   SubzoneName       323 non-null    object
 3   PlanningAreaId    323 non-null    int64
 4   PlanningAreaCode  323 non-null    object
 5   PlanningAreaName  323 non-null    object
dtypes: int64(2), object(4)
memory usage: 15.3+ KB

In [3]:
POI.describe()

                 Id  POI_InSubzone  POI_Latitude  POI_Longitude
count   7795.000000    7795.000000   7794.000000    7794.000000
mean    5263.029121     165.728031      1.343400     103.830187
std     3808.450653      84.952541      0.044990       0.075582
min        1.000000       1.000000      1.247763     103.621921
25%     1958.500000     107.000000      1.309787     103.774453
50%     3907.000000     168.000000      1.335406     103.842226
75%     9287.500000     233.000000      1.372411     103.882517
max    11450.000000     999.000000      1.467583     104.003593

In [4]:
Amenities.describe()

,PropertyID,Gym,Pool,Playground,Tennis,LapPool,KidsPool,Squash,Badminton,Basketball,BBQ,Jacuzzi,Security
count,2.400000e+03,2395.000000,2398.000000,2393.000000,2391.000000,2386.000000,2386.000000,2383.000000,2383.000000,2383.000000,2394.000000,2387.000000,2371.000000
mean,1.863589e+05,0.751148,0.879066,0.687840,0.518611,0.413244,0.584241,0.371800,0.304238,0.317667,0.748538,0.566401,0.832560
std,1.893191e+05,0.432438,0.326119,0.463472,0.499758,0.492519,0.492956,0.483387,0.460181,0.465667,0.433944,0.495675,0.373447
min,1.120000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.075600e+04,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,1.519280e+05,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
75%,3.146360e+05,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2.319184e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
SM_assets.describe()

,PropertyID,NumberofSchoolsWithin500Mts,NumberOfMRTsWithin500Mts,NumberOfBusStopsWithin500Mts,TimeToRafflesByCarInSeconds,TimeToRafflesByPublicTransportInSeconds,TimeToAirportByCarInSeconds,TimeToAirportByPublicTransportInSeconds
count,1.909500e+04,19095.000000,19095.000000,19095.000000,19095.000000,19095.000000,19095.000000,19095.000000
mean,1.174321e+06,0.803456,0.182613,12.040534,1056.654779,3135.487981,1311.039592,5942.292852
std,6.747659e+05,2.417979,0.408754,4.974948,321.024104,948.480289,429.093307,1480.310303
min,1.120000e+02,0.000000,0.000000,0.000000,90.000000,0.000000,415.000000,0.000000
25%,5.887280e+05,0.000000,0.000000,9.000000,829.000000,2430.000000,953.000000,4704.000000
50%,1.213968e+06,0.000000,0.000000,12.000000,1000.000000,3086.000000,1266.000000,5810.000000
75%,1.759352e+06,1.000000,0.000000,15.000000,1297.000000,3848.000000,1645.000000,7046.500000
max,2.319184e+06,46.000000,4.000000,31.000000,1863.000000,6084.000000,2345.000000,9723.000000

In [6]:
Sales.describe()

,Id,PropertyID,PropertyType,PropertyTenureType,PropertyNumberOfFloors,PropertynumberOfUnits,PropertyYearOfCompletion,PropertyInSubzone,PropertyLatitude,PropertyLongitude,FloorNoOfTransactedUnit,NumberOfBedroomsInTransactedUnit,TransactedPricePerSqFt,TransactionType
count,517591.000000,5.175910e+05,517591.000000,517591.000000,152153.000000,451278.000000,462689.000000,517591.000000,517591.000000,517591.000000,517591.000000,241531.000000,517591.000000,517591.000000
mean,258793.000070,9.662232e+05,4.467064,1.782384,17.900041,254.649374,1997.880321,180.398674,1.350370,103.845626,7.963278,2.688831,731.808127,1.447027
std,149415.795807,7.474431e+05,2.007677,0.413046,11.947095,250.533729,12.924244,77.045890,0.043432,0.067717,6.566301,0.489700,510.648617,0.869566
min,1.000000,1.120000e+02,1.000000,1.000000,2.000000,2.000000,1960.000000,2.000000,1.238204,103.685193,-3.000000,0.000000,76.470000,0.000000
25%,129395.500000,3.254720e+05,4.000000,2.000000,10.000000,96.000000,1987.000000,126.000000,1.316204,103.796693,3.000000,2.000000,353.470000,0.000000
50%,258793.000000,3.892000e+05,4.000000,2.000000,16.000000,136.000000,2000.000000,189.000000,1.346604,103.846493,7.000000,3.000000,552.160000,2.000000
75%,388190.500000,1.673504e+06,7.000000,2.000000,24.000000,350.000000,2009.000000,240.000000,1.377904,103.897793,11.000000,3.000000,984.330000,2.000000
max,517588.000000,2.335088e+06,7.000000,3.000000,70.000000,1390.000000,2019.000000,321.000000,1.461304,103.987793,70.000000,4.000000,6840.330000,2.000000

In [7]:
Subzones.describe()

        SubzoneId  PlanningAreaId
count  323.000000      323.000000
mean   162.000000       26.529412
std     93.386294       15.692154
min      1.000000        1.000000
25%     81.500000       13.000000
50%    162.000000       26.000000
75%    242.500000       41.000000
max    323.000000       55.000000

In [8]:
POI

,Id,POI_Type,POI_Name,POI_InSubzone,POI_Latitude,POI_Longitude
0,1,MRT,Yio Chu Kang,228,1.381758,103.844801
1,2,MRT,Expo,213,1.334549,103.961546
2,3,MRT,Marymount,236,1.348777,103.839413
3,4,MRT,Botanic Gardens,164,1.322229,103.815469
4,5,MRT,Braddell,148,1.340444,103.846800
...,...,...,...,...,...,...
7790,11434,MRT,Choa Chu Kang,220,1.385366,103.744095
7791,11435,MRT,Bukit Gombak,255,1.358632,103.751814
7792,11436,MRT,Bukit Batok,175,1.349022,103.749540
7793,11437,MRT,Punggol,310,1.404544,103.902034
7794,11450,MRT,Unknown,999,NaN,NaN

In [9]:
Amenities

,PropertyID,Gym,Pool,Playground,Tennis,Golf,Cafe,LapPool,KidsPool,Squash,Badminton,Basketball,BBQ,Jacuzzi,Security,Salon,Sauna,Shop
0,177968,0.0,1.0,1.0,1.0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,326704,1.0,1.0,1.0,0.0,0,0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0,1,0
2,363888,1.0,1.0,1.0,1.0,0,0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,1,0
3,438256,0.0,0.0,1.0,0.0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,2576,1.0,1.0,1.0,1.0,1,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,115696,1.0,1.0,1.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0,0,0
2396,121184,1.0,1.0,1.0,1.0,1,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1,1
2397,176288,1.0,1.0,1.0,1.0,1,0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0,1,0
2398,181776,0.0,1.0,1.0,1.0,0,0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0
2399,363552,1.0,1.0,1.0,0.0,0,0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0,1,0

In [10]:
SM_assets

,PropertyID,NumberofSchoolsWithin500Mts,NumberOfMRTsWithin500Mts,NumberOfBusStopsWithin500Mts,TimeToRafflesByCarInSeconds,TimeToRafflesByPublicTransportInSeconds,TimeToAirportByCarInSeconds,TimeToAirportByPublicTransportInSeconds
0,112,2,1,12,775,1596,1063,4180
1,224,3,1,14,720,1745,1149,4329
2,336,0,1,11,580,1712,1186,5801
3,448,0,0,7,995,3746,1524,7390
4,560,0,0,9,751,2653,794,5177
...,...,...,...,...,...,...,...,...
19090,2312576,0,0,9,1332,3792,1541,7106
19091,2312688,8,1,7,582,1431,1311,5520
19092,2314032,0,0,6,1050,3425,1515,6706
19093,2318624,0,0,7,1090,3020,1637,7492
19094,2319184,1,0,12,931,2867,1396,5811

In [11]:
Sales

,Id,PropertyID,PropertyType,PropertyTenureType,PropertyNumberOfFloors,PropertynumberOfUnits,PropertyYearOfCompletion,PropertyInSubzone,PropertyLatitude,PropertyLongitude,FloorNoOfTransactedUnit,NumberOfBedroomsInTransactedUnit,TransactedPricePerSqFt,TransactionType,TransactionDate
0,1,202160,7,1,30.0,87.0,1993.0,69,1.296504,103.893393,10,NaN,2082.00,2,03/30/13
1,2,332080,7,2,NaN,1093.0,1986.0,92,1.310904,103.936393,16,NaN,1105.23,2,03/29/13
2,3,378896,2,2,NaN,397.0,2005.0,216,1.380404,103.935293,7,NaN,850.23,2,03/29/13
3,4,32256,1,1,NaN,42.0,2015.0,163,1.312304,103.883493,7,NaN,1319.10,0,03/28/13
4,5,375984,2,2,18.0,297.0,2004.0,217,1.385304,103.842093,5,NaN,929.63,2,03/28/13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517586,517584,228704,3,1,NaN,NaN,NaN,116,1.326204,103.796393,0,NaN,1988.34,2,05/24/12
517587,517585,228704,3,1,NaN,NaN,NaN,116,1.325904,103.797893,0,NaN,1765.23,2,05/28/12
517588,517586,288064,6,1,NaN,NaN,NaN,116,1.324104,103.796393,0,NaN,1935.48,2,6/7/2012
517589,517587,228704,3,1,NaN,NaN,NaN,116,1.324904,103.794393,0,NaN,1880.18,2,10/2/2014
517590,517588,228704,3,1,NaN,NaN,NaN,116,1.326204,103.798793,0,NaN,1793.36,2,12/17/15

In [12]:
Subzones

,SubzoneId,SubzoneCode,SubzoneName,PlanningAreaId,PlanningAreaCode,PlanningAreaName
0,181,BSSZ03,Bishan East,1,BS,Bishan
1,186,BSSZ02,Marymount,1,BS,Bishan
2,236,BSSZ01,Upper Thomson,1,BS,Bishan
3,237,BKSZ02,Hong Kah North,2,BK,Bukit Batok
4,233,BKSZ05,Hillview,2,BK,Bukit Batok
...,...,...,...,...,...,...
318,120,RCSZ01,Farrer Park,53,RC,Rochor
319,15,SRSZ01,Robertson Quay,54,SR,Singapore River
320,3,SRSZ03,Boat Quay,54,SR,Singapore River
321,8,SRSZ02,Clarke Quay,54,SR,Singapore River
322,23,SVSZ01,Straits View,55,SV,Straits View

## 2. Data Preprocessing

### Insights from Dataset Exploration

Several preprocessing steps were identified after reviewing the dataset structure, missing values, and data quality:

- The POI dataset contained one row with missing values, which was removed to maintain data consistency.
  
- The Amenities dataset contained multiple missing (NaN) values. As these values likely indicate the absence of an amenity, they were replaced with 0 to represent that the amenity does not exist for the property.
  
- The PropertyNumberOfFloors column in the Sales Transactions dataset contained more than 50% missing values. Due to the high proportion of incomplete data, the column was removed from the analysis.
  
- The NumberOfBedroomsInTransactedUnit column also contained a significant number of missing values. Missing entries were replaced with -1 to indicate unknown bedroom counts while preserving the records for analysis.

- Missing values in PropertyYearOfCompletion and PropertynumberOfUnits were filled using the median values of their respective columns to reduce the impact of missing data while maintaining the overall distribution of the dataset.

In [13]:
# Drop duplicates
POI = POI.drop_duplicates()
Amenities = Amenities.drop_duplicates()
SM_assets = SM_assets.drop_duplicates()
Sales = Sales.drop_duplicates()
Subzones = Subzones.drop_duplicates()

# Drop row from POI
POI = POI.dropna(subset=['POI_Latitude', 'POI_Longitude'])

# Fill NaN with 2 (does not exist)
Amenities = Amenities.fillna(2)

# Drop high-missing column
Sales = Sales.drop(columns=['PropertyNumberOfFloors'])

# Fill bedroom missing values with -1 (Unknown)
Sales['NumberOfBedroomsInTransactedUnit'] = (
    Sales['NumberOfBedroomsInTransactedUnit'].fillna(-1)
)

# Fill columns with median
Sales['PropertyYearOfCompletion'] = (
    Sales['PropertyYearOfCompletion'].fillna(
        Sales['PropertyYearOfCompletion'].median()
    )
)

Sales['PropertynumberOfUnits'] = (
    Sales['PropertynumberOfUnits'].fillna(
        Sales['PropertynumberOfUnits'].median()
    )
)

## 3. Dataset Merging

The datasets were merged into a single consolidated dataset to support further analysis and Tableau visualisation. This will make it easier to create visualisations in Tableau without having to manually merge the datasets in the software itself.

- To merge the datasets, the key column PropertyID will be used to first merge the Sales, Amenities and SM_assets dataset.

- To merge the final POI and Subzone datasets, SubzoneId is used. This will create the final dataset to be used in Tableau. In addition, a new column will be created to count the number of POIs in the vicinity (by subzones) of each property.

- To prepare for dataset merging, final checks and data standardization will be carried out first.

In [14]:
# final check for any NaN values in all the dataframes
POI.isnull().sum()

Id               0
POI_Type         0
POI_Name         0
POI_InSubzone    0
POI_Latitude     0
POI_Longitude    0
dtype: int64

In [15]:
Amenities.isnull().sum()

PropertyID    0
Gym           0
Pool          0
Playground    0
Tennis        0
Golf          0
Cafe          0
LapPool       0
KidsPool      0
Squash        0
Badminton     0
Basketball    0
BBQ           0
Jacuzzi       0
Security      0
Salon         0
Sauna         0
Shop          0
dtype: int64

In [16]:
SM_assets.isnull().sum()

PropertyID                                 0
NumberofSchoolsWithin500Mts                0
NumberOfMRTsWithin500Mts                   0
NumberOfBusStopsWithin500Mts               0
TimeToRafflesByCarInSeconds                0
TimeToRafflesByPublicTransportInSeconds    0
TimeToAirportByCarInSeconds                0
TimeToAirportByPublicTransportInSeconds    0
dtype: int64

In [17]:
Sales.isnull().sum()

Id                                  0
PropertyID                          0
PropertyType                        0
PropertyTenureType                  0
PropertynumberOfUnits               0
PropertyYearOfCompletion            0
PropertyInSubzone                   0
PropertyLatitude                    0
PropertyLongitude                   0
FloorNoOfTransactedUnit             0
NumberOfBedroomsInTransactedUnit    0
TransactedPricePerSqFt              0
TransactionType                     0
TransactionDate                     0
dtype: int64

In [18]:
Subzones.isnull().sum()

SubzoneId           0
SubzoneCode         0
SubzoneName         0
PlanningAreaId      0
PlanningAreaCode    0
PlanningAreaName    0
dtype: int64

In [19]:
# Standardize date format
Sales['TransactionDate'] = pd.to_datetime(
    Sales['TransactionDate'],
    errors='coerce'
)

C:\Users\User\AppData\Local\Temp\ipykernel_25908\611359084.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Sales['TransactionDate'] = pd.to_datetime(

In [20]:
# Check if standardization was successful
Sales['TransactionDate'].isnull().sum()

0

### All Datasets are filled with no missing values, especially for PropertyID, which will be used as the key to merge Sales, Amenities and SM_assets first.

In [21]:
# Merge first three datasets
Sales_Amenities = Sales.merge(Amenities, on='PropertyID', how='left')
Sales_Full = Sales_Amenities.merge(SM_assets, on='PropertyID', how='left')

In [22]:
# Check new dataset
Sales_Full.isnull().sum()

Id                                              0
PropertyID                                      0
PropertyType                                    0
PropertyTenureType                              0
PropertynumberOfUnits                           0
PropertyYearOfCompletion                        0
PropertyInSubzone                               0
PropertyLatitude                                0
PropertyLongitude                               0
FloorNoOfTransactedUnit                         0
NumberOfBedroomsInTransactedUnit                0
TransactedPricePerSqFt                          0
TransactionType                                 0
TransactionDate                                 0
Gym                                        274880
Pool                                       274880
Playground                                 274880
Tennis                                     274880
Golf                                       274880
Cafe                                       274880
LapPool                                    274880
KidsPool                                   274880
Squash                                     274880
Badminton                                  274880
Basketball                                 274880
BBQ                                        274880
Jacuzzi                                    274880
Security                                   274880
Salon                                      274880
Sauna                                      274880
Shop                                       274880
NumberofSchoolsWithin500Mts                   330
NumberOfMRTsWithin500Mts                      330
NumberOfBusStopsWithin500Mts                  330
TimeToRafflesByCarInSeconds                   330
TimeToRafflesByPublicTransportInSeconds       330
TimeToAirportByCarInSeconds                   330
TimeToAirportByPublicTransportInSeconds       330
dtype: int64

there are multiple NaN values for some columns which will be resolved later.

#### For the last two datasets, Subzones will be merged first as POI relies on the Subzone due to the hierarchical structure of the data. The Property dataset links each property to a specific subzone. To match POIs to the relevant properties, The POI dataset uses the subzone ID to identify which properties should link to which POIs.

In [23]:
# Merge Subzones first 
Sales_Full = Sales_Full.merge(
    Subzones,
    left_on='PropertyInSubzone',
    right_on='SubzoneId',
    how='left'
)

In [24]:
# create new column for POI count (used for Tableau visulisation)
POI_features = POI.pivot_table(
    index='POI_InSubzone',
    columns='POI_Type',
    aggfunc='size',
    fill_value=0
).reset_index()

# Merge POI last
Sales_Full = Sales_Full.merge(
    POI_features,
    left_on='PropertyInSubzone',
    right_on='POI_InSubzone',
    how='left'
)

In [25]:
# Check Master Dataset
Sales_Full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517588 entries, 0 to 517587
Data columns (total 64 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   Id                                       517588 non-null  int64
 1   PropertyID                               517588 non-null  int64
 2   PropertyType                             517588 non-null  int64
 3   PropertyTenureType                       517588 non-null  int64
 4   PropertynumberOfUnits                    517588 non-null  float64
 5   PropertyYearOfCompletion                 517588 non-null  float64
 6   PropertyInSubzone                        517588 non-null  int64
 7   PropertyLatitude                         517588 non-null  float64
 8   PropertyLongitude                        517588 non-null  float64
 9   FloorNoOfTransactedUnit                  517588 non-null  int64
 10  NumberOfBedroomsInTransactedUnit         517588 non-null  float64
 11  TransactedPricePerSqFt                   517588 non-null  float64
 12  TransactionType                          517588 non-null  int64
 13  TransactionDate                          517588 non-null  datetime64[ns]
 14  Gym                                      242708 non-null  float64
 15  Pool                                     242708 non-null  float64
 16  Playground                               242708 non-null  float64
 17  Tennis                                   242708 non-null  float64
 18  Golf                                     242708 non-null  object
 19  Cafe                                     242708 non-null  object
 20  LapPool                                  242708 non-null  float64
 21  KidsPool                                 242708 non-null  float64
 22  Squash                                   242708 non-null  float64
 23  Badminton                                242708 non-null  float64
 24  Basketball                               242708 non-null  float64
 25  BBQ                                      242708 non-null  float64
 26  Jacuzzi                                  242708 non-null  float64
 27  Security                                 242708 non-null  float64
 28  Salon                                    242708 non-null  object
 29  Sauna                                    242708 non-null  object
 30  Shop                                     242708 non-null  object
 31  NumberofSchoolsWithin500Mts              517258 non-null  float64
 32  NumberOfMRTsWithin500Mts                 517258 non-null  float64
 33  NumberOfBusStopsWithin500Mts             517258 non-null  float64
 34  TimeToRafflesByCarInSeconds              517258 non-null  float64
 35  TimeToRafflesByPublicTransportInSeconds  517258 non-null  float64
 36  TimeToAirportByCarInSeconds              517258 non-null  float64
 37  TimeToAirportByPublicTransportInSeconds  517258 non-null  float64
 38  SubzoneId                                517588 non-null  int64
 39  SubzoneCode                              517588 non-null  object
 40  SubzoneName                              517588 non-null  object
 41  PlanningAreaId                           517588 non-null  int64
 42  PlanningAreaCode                         517588 non-null  object
 43  PlanningAreaName                         517588 non-null  object
 44  POI_InSubzone                            517588 non-null  int64
 45  BUSstop                                  517588 non-null  int64
 46  Bus Stop                                 517588 non-null  int64
 47  Cinema                                   517588 non-null  int64
 48  Clinic                                   517588 non-null  int64
 49  Community Club                           517588 non-null  int64
 50  Hospital                                 517588 non-null  int64
 51  Industrial                               517588 non-null  int64
 52  Junior College                           517588 non-null  int64
 53  Kindergarten                             517588 non-null  int64
 54  Library                                  517588 non-null  int64
 55  MRT                                      517588 non-null  int64
 56  Nursing Home                             517588 non-null  int64
 57  Office                                   517588 non-null  int64
 58  Other                                    517588 non-null  int64
 59  Police Establishment                     517588 non-null  int64
 60  Primary School                           517588 non-null  int64
 61  Private Institution                      517588 non-null  int64
 62  Secondary School                         517588 non-null  int64
 63  Shopping Mall                            517588 non-null  int64
dtypes: datetime64[ns](1), float64(25), int64(29), object(9)
memory usage: 252.7+ MB

#### With all the datasets merged, missing values can now be dealt with.

In [26]:
# Reformatting of certain amenities columns

# Check unique values for object columns
cols = ['Golf','Cafe','Salon','Sauna','Shop']

for col in cols:
    print(col, Sales_Full[col].unique())


for col in cols:
    
    nan_count = (Sales_Full[col] == 'nan').sum()
    
    nil_count = (Sales_Full[col] == 'NIL').sum()
    
    print(f"{col}")
    print(f"NaN Count: {nan_count}")
    print(f"NIL Count: {nil_count}")
    print()

Golf ['1' '0' 2 nan 'NIL']
Cafe ['0' 2 nan '1' 'NIL']
Salon ['0' 2 nan 'NIL']
Sauna ['0' '1' 2 nan]
Shop ['0' '1' 2 nan]
Golf
NaN Count: 0
NIL Count: 26

Cafe
NaN Count: 0
NIL Count: 26

Salon
NaN Count: 0
NIL Count: 26

Sauna
NaN Count: 0
NIL Count: 0

Shop
NaN Count: 0
NIL Count: 0

In [27]:
# Replace with integers
cols = ['Golf','Cafe','Salon','Sauna','Shop']

Sales_Full[cols] = Sales_Full[cols].replace('NIL', 2)
Sales_Full[cols] = Sales_Full[cols].replace('nan', 2)

In [28]:
# Reformat into float64
cols = ['Golf','Cafe','Salon','Sauna','Shop']
Sales_Full[cols] = Sales_Full[cols].astype(float)

In [29]:
# Check reformatting success
Sales_Full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517588 entries, 0 to 517587
Data columns (total 64 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   Id                                       517588 non-null  int64
 1   PropertyID                               517588 non-null  int64
 2   PropertyType                             517588 non-null  int64
 3   PropertyTenureType                       517588 non-null  int64
 4   PropertynumberOfUnits                    517588 non-null  float64
 5   PropertyYearOfCompletion                 517588 non-null  float64
 6   PropertyInSubzone                        517588 non-null  int64
 7   PropertyLatitude                         517588 non-null  float64
 8   PropertyLongitude                        517588 non-null  float64
 9   FloorNoOfTransactedUnit                  517588 non-null  int64
 10  NumberOfBedroomsInTransactedUnit         517588 non-null  float64
 11  TransactedPricePerSqFt                   517588 non-null  float64
 12  TransactionType                          517588 non-null  int64
 13  TransactionDate                          517588 non-null  datetime64[ns]
 14  Gym                                      242708 non-null  float64
 15  Pool                                     242708 non-null  float64
 16  Playground                               242708 non-null  float64
 17  Tennis                                   242708 non-null  float64
 18  Golf                                     242708 non-null  float64
 19  Cafe                                     242708 non-null  float64
 20  LapPool                                  242708 non-null  float64
 21  KidsPool                                 242708 non-null  float64
 22  Squash                                   242708 non-null  float64
 23  Badminton                                242708 non-null  float64
 24  Basketball                               242708 non-null  float64
 25  BBQ                                      242708 non-null  float64
 26  Jacuzzi                                  242708 non-null  float64
 27  Security                                 242708 non-null  float64
 28  Salon                                    242708 non-null  float64
 29  Sauna                                    242708 non-null  float64
 30  Shop                                     242708 non-null  float64
 31  NumberofSchoolsWithin500Mts              517258 non-null  float64
 32  NumberOfMRTsWithin500Mts                 517258 non-null  float64
 33  NumberOfBusStopsWithin500Mts             517258 non-null  float64
 34  TimeToRafflesByCarInSeconds              517258 non-null  float64
 35  TimeToRafflesByPublicTransportInSeconds  517258 non-null  float64
 36  TimeToAirportByCarInSeconds              517258 non-null  float64
 37  TimeToAirportByPublicTransportInSeconds  517258 non-null  float64
 38  SubzoneId                                517588 non-null  int64
 39  SubzoneCode                              517588 non-null  object
 40  SubzoneName                              517588 non-null  object
 41  PlanningAreaId                           517588 non-null  int64
 42  PlanningAreaCode                         517588 non-null  object
 43  PlanningAreaName                         517588 non-null  object
 44  POI_InSubzone                            517588 non-null  int64
 45  BUSstop                                  517588 non-null  int64
 46  Bus Stop                                 517588 non-null  int64
 47  Cinema                                   517588 non-null  int64
 48  Clinic                                   517588 non-null  int64
 49  Community Club                           517588 non-null  int64
 50  Hospital                                 517588 non-null  int64
 51  Industrial                               517588 non-null  int64
 52  Junior College                           517588 non-null  int64
 53  Kindergarten                             517588 non-null  int64
 54  Library                                  517588 non-null  int64
 55  MRT                                      517588 non-null  int64
 56  Nursing Home                             517588 non-null  int64
 57  Office                                   517588 non-null  int64
 58  Other                                    517588 non-null  int64
 59  Police Establishment                     517588 non-null  int64
 60  Primary School                           517588 non-null  int64
 61  Private Institution                      517588 non-null  int64
 62  Secondary School                         517588 non-null  int64
 63  Shopping Mall                            517588 non-null  int64
dtypes: datetime64[ns](1), float64(30), int64(29), object(4)
memory usage: 252.7+ MB

In [30]:
# Fill NaN with 2 (data unavailable)
cols = ['Gym','Pool','Playground','Tennis','Golf','Cafe','LapPool','KidsPool','Squash','Badminton','Basketball','BBQ','Jacuzzi','Security','Salon','Sauna','Shop']
Sales_Full[cols] = Sales_Full[cols].fillna(2)

In [31]:
# Fill NaN with median of column
sm_cols = [
    'NumberofSchoolsWithin500Mts',
    'NumberOfMRTsWithin500Mts',
    'NumberOfBusStopsWithin500Mts',
    'TimeToRafflesByCarInSeconds',
    'TimeToRafflesByPublicTransportInSeconds',
    'TimeToAirportByCarInSeconds',
    'TimeToAirportByPublicTransportInSeconds'
]

for col in sm_cols:
    Sales_Full[col] = Sales_Full[col].fillna(Sales_Full[col].median())

In [32]:
# Check all rows are filled
Sales_Full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517588 entries, 0 to 517587
Data columns (total 64 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   Id                                       517588 non-null  int64
 1   PropertyID                               517588 non-null  int64
 2   PropertyType                             517588 non-null  int64
 3   PropertyTenureType                       517588 non-null  int64
 4   PropertynumberOfUnits                    517588 non-null  float64
 5   PropertyYearOfCompletion                 517588 non-null  float64
 6   PropertyInSubzone                        517588 non-null  int64
 7   PropertyLatitude                         517588 non-null  float64
 8   PropertyLongitude                        517588 non-null  float64
 9   FloorNoOfTransactedUnit                  517588 non-null  int64
 10  NumberOfBedroomsInTransactedUnit         517588 non-null  float64
 11  TransactedPricePerSqFt                   517588 non-null  float64
 12  TransactionType                          517588 non-null  int64
 13  TransactionDate                          517588 non-null  datetime64[ns]
 14  Gym                                      517588 non-null  float64
 15  Pool                                     517588 non-null  float64
 16  Playground                               517588 non-null  float64
 17  Tennis                                   517588 non-null  float64
 18  Golf                                     517588 non-null  float64
 19  Cafe                                     517588 non-null  float64
 20  LapPool                                  517588 non-null  float64
 21  KidsPool                                 517588 non-null  float64
 22  Squash                                   517588 non-null  float64
 23  Badminton                                517588 non-null  float64
 24  Basketball                               517588 non-null  float64
 25  BBQ                                      517588 non-null  float64
 26  Jacuzzi                                  517588 non-null  float64
 27  Security                                 517588 non-null  float64
 28  Salon                                    517588 non-null  float64
 29  Sauna                                    517588 non-null  float64
 30  Shop                                     517588 non-null  float64
 31  NumberofSchoolsWithin500Mts              517588 non-null  float64
 32  NumberOfMRTsWithin500Mts                 517588 non-null  float64
 33  NumberOfBusStopsWithin500Mts             517588 non-null  float64
 34  TimeToRafflesByCarInSeconds              517588 non-null  float64
 35  TimeToRafflesByPublicTransportInSeconds  517588 non-null  float64
 36  TimeToAirportByCarInSeconds              517588 non-null  float64
 37  TimeToAirportByPublicTransportInSeconds  517588 non-null  float64
 38  SubzoneId                                517588 non-null  int64
 39  SubzoneCode                              517588 non-null  object
 40  SubzoneName                              517588 non-null  object
 41  PlanningAreaId                           517588 non-null  int64
 42  PlanningAreaCode                         517588 non-null  object
 43  PlanningAreaName                         517588 non-null  object
 44  POI_InSubzone                            517588 non-null  int64
 45  BUSstop                                  517588 non-null  int64
 46  Bus Stop                                 517588 non-null  int64
 47  Cinema                                   517588 non-null  int64
 48  Clinic                                   517588 non-null  int64
 49  Community Club                           517588 non-null  int64
 50  Hospital                                 517588 non-null  int64
 51  Industrial                               517588 non-null  int64
 52  Junior College                           517588 non-null  int64
 53  Kindergarten                             517588 non-null  int64
 54  Library                                  517588 non-null  int64
 55  MRT                                      517588 non-null  int64
 56  Nursing Home                             517588 non-null  int64
 57  Office                                   517588 non-null  int64
 58  Other                                    517588 non-null  int64
 59  Police Establishment                     517588 non-null  int64
 60  Primary School                           517588 non-null  int64
 61  Private Institution                      517588 non-null  int64
 62  Secondary School                         517588 non-null  int64
 63  Shopping Mall                            517588 non-null  int64
dtypes: datetime64[ns](1), float64(30), int64(29), object(4)
memory usage: 252.7+ MB

Identifier columns will be dropped as they are unique and will not be useful in creating visualisations.

In [33]:
# Check bus stop columns since there are multiple
Sales_Full['BUSstop'].unique()

array([0, 5], dtype=int64)

In [34]:
Sales_Full['Bus Stop'].unique()

array([18, 11, 39, 45, 17, 14,  8, 25, 22,  7, 79, 48, 35, 55, 10,  9,  5,
       71,  6, 24, 33, 13, 41, 29, 30, 23,  1, 16, 12, 32, 15, 50, 34, 26,
        3,  0,  2, 36, 21,  4, 38, 27, 47, 19, 42, 20, 37, 31],
      dtype=int64)

'BUSstop' column will be dropped, anomalous column

In [35]:
# Create list of columns to drop
cols_to_drop = [
    'Id',
    'PropertyID',
    'SubzoneId',
    'SubzoneCode',
    'PlanningAreaId',
    'PlanningAreaCode',
    'POI_InSubzone',
    'BUSstop'
]

# Apply to dataset
Sales_Full = Sales_Full.drop(columns=cols_to_drop)

In [36]:
# Final check
Sales_Full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517588 entries, 0 to 517587
Data columns (total 56 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   PropertyType                             517588 non-null  int64
 1   PropertyTenureType                       517588 non-null  int64
 2   PropertynumberOfUnits                    517588 non-null  float64
 3   PropertyYearOfCompletion                 517588 non-null  float64
 4   PropertyInSubzone                        517588 non-null  int64
 5   PropertyLatitude                         517588 non-null  float64
 6   PropertyLongitude                        517588 non-null  float64
 7   FloorNoOfTransactedUnit                  517588 non-null  int64
 8   NumberOfBedroomsInTransactedUnit         517588 non-null  float64
 9   TransactedPricePerSqFt                   517588 non-null  float64
 10  TransactionType                          517588 non-null  int64
 11  TransactionDate                          517588 non-null  datetime64[ns]
 12  Gym                                      517588 non-null  float64
 13  Pool                                     517588 non-null  float64
 14  Playground                               517588 non-null  float64
 15  Tennis                                   517588 non-null  float64
 16  Golf                                     517588 non-null  float64
 17  Cafe                                     517588 non-null  float64
 18  LapPool                                  517588 non-null  float64
 19  KidsPool                                 517588 non-null  float64
 20  Squash                                   517588 non-null  float64
 21  Badminton                                517588 non-null  float64
 22  Basketball                               517588 non-null  float64
 23  BBQ                                      517588 non-null  float64
 24  Jacuzzi                                  517588 non-null  float64
 25  Security                                 517588 non-null  float64
 26  Salon                                    517588 non-null  float64
 27  Sauna                                    517588 non-null  float64
 28  Shop                                     517588 non-null  float64
 29  NumberofSchoolsWithin500Mts              517588 non-null  float64
 30  NumberOfMRTsWithin500Mts                 517588 non-null  float64
 31  NumberOfBusStopsWithin500Mts             517588 non-null  float64
 32  TimeToRafflesByCarInSeconds              517588 non-null  float64
 33  TimeToRafflesByPublicTransportInSeconds  517588 non-null  float64
 34  TimeToAirportByCarInSeconds              517588 non-null  float64
 35  TimeToAirportByPublicTransportInSeconds  517588 non-null  float64
 36  SubzoneName                              517588 non-null  object
 37  PlanningAreaName                         517588 non-null  object
 38  Bus Stop                                 517588 non-null  int64
 39  Cinema                                   517588 non-null  int64
 40  Clinic                                   517588 non-null  int64
 41  Community Club                           517588 non-null  int64
 42  Hospital                                 517588 non-null  int64
 43  Industrial                               517588 non-null  int64
 44  Junior College                           517588 non-null  int64
 45  Kindergarten                             517588 non-null  int64
 46  Library                                  517588 non-null  int64
 47  MRT                                      517588 non-null  int64
 48  Nursing Home                             517588 non-null  int64
 49  Office                                   517588 non-null  int64
 50  Other                                    517588 non-null  int64
 51  Police Establishment                     517588 non-null  int64
 52  Primary School                           517588 non-null  int64
 53  Private Institution                      517588 non-null  int64
 54  Secondary School                         517588 non-null  int64
 55  Shopping Mall                            517588 non-null  int64
dtypes: datetime64[ns](1), float64(30), int64(23), object(2)
memory usage: 221.1+ MB

In [37]:
# Remove spaces from column names (standardize)
Sales_Full.columns = Sales_Full.columns.str.strip()

## 4. Export Final Dataset
The Final dataset including all the neccessary columns after the merge and cleaning will be exported as an excel file for Tableau.

In [38]:
# Export as xlsx file
Sales_Full.to_excel(
    r'C:\Downloads\final_dataset.xlsx',
    index=False
)